package gothriftpooltest

import (
	"fmt"
	"github.com/koofr/gothriftpool"
	"testing"
)

const testGeneratorExpected = `// Autogenerated by gothriftpool generator
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package myserviceproxy

import (
	"errors"
	"github.com/koofr/go-resourcepool"

	"github.com/koofr/gothriftpool/gothriftpooltest/myservice"
)

var CreateResourceErr = errors.New("myservice.MyServiceClient resource could not be created")

type ClientFactory func() (*myservice.MyServiceClient, error)

type resource struct {
	client *myservice.MyServiceClient
	closed bool
}

func (r *resource) Close() {
	r.closed = true
	r.client.Transport.Close()
}

func (r *resource) IsClosed() bool {
	return r.closed
}

type Proxy struct {
	clientFactory ClientFactory
	pool          *resourcepool.ResourcePool
}

func New(clientFactory ClientFactory, idleCapacity int, maxResources int) *Proxy {
	p := &Proxy{
		clientFactory: clientFactory,
	}

	p.pool = resourcepool.NewResourcePool(p.createResource, idleCapacity, maxResources)

	return p
}

func (p *Proxy) Close() {
	p.pool.Close()
}

func (p *Proxy) createResource() (r resourcepool.Resource, err error) {
	client, err := p.clientFactory()

	if err != nil {
		return
	}

	r = &resource{client, false}

	return
}

func (p *Proxy) getResource() (resourcepool.Resource, error) {
	for i := 0; i < 2; i++ {
		r, err := p.pool.Acquire()

		if err != nil {
			p.pool.Empty()

			continue
		}

		err = r.(*resource).client.Ping()

		if err != nil {
			r.Close()

			p.pool.Release(r)

			p.pool.Empty()

			continue
		}

		return r, nil
	}

	return nil, CreateResourceErr
}

func (p *Proxy) Ping() (err error) {
	poolResource, err := p.getResource()

	if err != nil {
		return
	}

	defer p.pool.Release(poolResource)

	return poolResource.(*resource).client.Ping()
}

func (p *Proxy) GetResponse(id myservice.UUID, req *myservice.MyRequest) (r *myservice.MyResponse, err error) {
	poolResource, err := p.getResource()

	if err != nil {
		return
	}

	defer p.pool.Release(poolResource)

	return poolResource.(*resource).client.GetResponse(id, req)
}
`

func TestGenerator(t *testing.T) {
	iface := "myservice.MyService"

	generator, err := gothriftpool.NewGenerator(iface)

	if err != nil {
		t.Error(err)
	}

	code, err := generator.Generate()

	if err != nil {
		t.Error(err)
	}

	if string(code) != testGeneratorExpected {
		t.Error("Generated code doesn't not match expected.")
		fmt.Println("Generated:")
		fmt.Println("*****")
		fmt.Print(string(code))
		fmt.Println("*****")
	}
}
